---
# User/Password Credentials
jenkins_user_pass_credentials:
  - tower-admin-user:
      username: ""                            # Ansible Tower admin username
      password: ""                            # Ansible Tower admin password
      description: "Ansible Tower Admin User"
  - githubjenkins:
      username: ""                            # Github username
      password: ""                            # Github password/token
      description: "GitHub Credentials"
  - integreatly-jira-bot:
      username: ""                            # JIRA username
      password: ""                            # JIRA password
      description: "Jira Bot Credentials"
  - intly-redhat-registry-sa:
      username: ""                            # Red Hat registry username
      password: ""                            # Red Hat registry password/token
      description: "Red Hat Registry Credentials"
  - tower-openshift-cluster-credentials:
      username: ""                            # Openshift username
      password: ""                            # Openshift password
      description: "Credentials for OpenShift clusters provisioned by Ansible Tower"

# SSH User with Private Key Credentials
jenkins_ssh_user_key_credentials:
  - jenkinsgithub:
      username: ""                            # Github username
      private_key: ""                         # Github private key
      passphrase: ""
      description: "GitHub SSH Credentials"
  - pds-bastion-pem:
      username: ""                            # PDS Bastion username
      private_key: ""                         # PDS Bastion private key
      passphrase: ""
      description: "PDS Bastion Pem"
  - tower-provisioner-pem:
      username: ""                            # Cluster username
      private_key: ""                         # Cluster private key
      passphrase: ""
      description: "SSH key for accessing clusters created by Ansible Tower"

# Secret Text Credentials
jenkins_secret_text_credentials:
  - aws-jenkins-integreatly:
      id: ""                                   # AWS client ID
      secret: ""                               # AWS secret token
      description: "AWS Client ID/Token"
