---
# Ansible Tower Configuration
ansible_tower_installations:
  - display_name: ""                          # Ansible Tower display name
    url: ""                                   # Ansible Tower url i.e. https://tower.example.com/
    credentials_id: "tower-admin-user"        # Credential ID where the tower admin username/password is stored
    trust_cert: false                         # Set to true to force Jenkins to ignore the cert presented by Ansible Tower
    enable_debugging: false                   # Set to true to enable debugging messages to be printed in the Jenkins log

# AWS SQS Configuration
aws_sqs_queues:
  - nameOrUrl: "https://sqs.eu-west-1.amazonaws.com/225726651034/delorean-demo-github-wh-queue.fifo"                             # Name or url of your message queue in AWS SQS
    credentialsId: "aws-jenkins-integreatly"  # Credential ID where the AWS client ID/token is stored
    waitTimeSeconds: "20"                     # Time to wait for a message to arrive in the queue (in seconds)
    maxNumberOfMessages: "1"                  # Maximum number of messages to receive per request
