---
- set_fact:
    base_dir: "{{ playbook_dir | dirname}}"

# Create config file for configuring the delorean jobs
- name: Generate jenkins config template
  template:
    src: "jenkins-config.ini.j2"
    dest: "{{base_dir}}/jenkins-config.ini"

- name: "Configure Delorean Jobs"
  shell: "sh ./scripts/configure_jenkins.sh ./scripts/jenkins-config.ini"
  args:
    chdir: "{{ base_dir }}/../"