---
apiVersion: v1
kind: Template
labels:
  template: intly-base-image-template
metadata:
  name: intly-base-image
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${IMAGE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${IMAGE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGE_NAME}:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/${GITHUB_ORG}/${GITHUB_REPO}
        ref: ${GITHUB_REF}
      contextDir: ${CONTEXT_DIR}
      type: Git
    strategy:
      dockerStrategy:
          noCache: true
          forcePull: true
          dockerfilePath: ${DOCKERFILE_PATH}
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange

parameters:
- description: The name of the github organization to reference in the configuration
  displayName: Github Organization
  name: GITHUB_ORG
  value: integr8ly
- description: The name of the github repo to reference in the configuration
  displayName: Github Repo
  name: GITHUB_REPO
  value: ci-cd
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: GITHUB_REF
  value: master
- description: The name of the OpenShift Image Stream name
  name: IMAGE_NAME
  value: intly-base-image
- description: The directory that contains the Dockerfile
  name: CONTEXT_DIR
  value: openshift-ci
- description: The dockerfile path
  name: DOCKERFILE_PATH
  value: Dockerfile.tools
