---
- hosts: all
  gather_facts: no
  tasks:
    - name: Preflight Checks
      include_role:
        name: preflight_checks
    - name: Install Plugins
      include_role:
        name: install_plugins
    - name: Add credentials
      include_role:
        name: add_credentials
    - name: Configure Global Settings
      include_role:
        name: configure_global_settings
    - name: Configure Delorean Jobs
      include_role:
        name: configure_delorean_jobs
      when: configure_delorean_jobs is defined and configure_delorean_jobs == 'true'