---

- name: Configure Delorean shared pipline library
  jenkins_script:
    script: "{{ lookup('file', 'configure_global_library.groovy') }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    validate_certs: no
    args:
      library_name: "{{ delorean_shared_library_name }}"
      gitUrl: "{{ delorean_shared_library_git_url }}"
      default_version: "{{ delorean_shared_library_version }}"
      load_implicit: "{{ delorean_shared_library_load_implicit }}"
  register: configure_global_library
  changed_when: not configure_global_library.failed

- name: Configure Ansible Tower settings
  jenkins_script:
    script: "{{ lookup('file', 'configure_ansible_tower.groovy') }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    validate_certs: no
    args:
      tower_installations: "{{ ansible_tower_installations | to_json }}"
  register: configure_ansible_tower
  changed_when: not configure_ansible_tower.failed

- set_fact:
    queues: "{{ aws_sqs_queues }}"

- name: Configure Amazon SQS Queue
  jenkins_script:
    script: "{{ lookup('file', 'configure_aws_sqs_queue.groovy') }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    validate_certs: no
    args:
      sqs_queues: "{{ queues | to_json}}"
  register: configure_aws_sqs
  changed_when: not configure_aws_sqs.failed