---

- name: Configure Delorean shared pipline library
  jenkins_script:
    script: "{{ lookup('file', 'configure_global_library.groovy') }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    validate_certs: no
    args:
      library_name: "{{ delorean_shared_library_name }}"
      gitUrl: "{{ delorean_shared_library_git_url }}"
      default_version: "{{ delorean_shared_library_version }}"
      load_implicit: "{{ delorean_shared_library_load_implicit }}"
  register: configure_global_library
  changed_when: not configure_global_library.failed
